export const FETCH_APPS_START = 'FETCH_APPS_START';
export const FETCH_APPS_SUCCESS = 'FETCH_APPS_SUCCESS';
export const FETCH_APPS_FAILURE = 'FETCH_APPS_FAILURE';
export const CHANGE_DEVICE_TYPE = 'CHANGE_DEVICE_TYPE';